import { StyleSheet } from 'react-native';

export const SellStyles = StyleSheet.create({
    image: {
        width: 200, 
        height: 200,
        borderRadius: 15,
    },
    add: {
        marginTop: 10,
        marginBottom: 10,
        width: 43,
        height: 43,
        backgroundColor: '#3aa4de',
        borderRadius: 50,
        alignItems: 'center',
        justifyContent: 'center',
        paddingLeft: 1,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 12,
        },
        shadowOpacity: 0.58,
        shadowRadius: 16.00,
        elevation: 10,
    },
    del: {
        width: 25,
        height: 25,
        backgroundColor: 'red',
        borderRadius: 25,
        paddingTop: 2,
        paddingLeft: 1,
        alignItems: 'center',
        position: 'absolute',
        top: 5,
        left: 170,
    },
    addImage: {
        justifyContent: 'center',
        alignItems: 'center',
        width: 200,
        height: 200,
        borderRadius: 15,
        borderStyle: 'dashed',
        borderColor: 'gray',
        borderWidth: 2,
    },
    pickerContainer:{
        width: '70%',
        borderRadius: 30,
        overflow: 'hidden',
        marginTop: 20,
        marginBottom: 10,
    },
    picker: {
        backgroundColor: '#93a8ac',
        color: '#424b54',
    },
    sendBtn: {
        width: '70%',
        height: 35,
        backgroundColor: '#80bfa1',
        borderRadius: 20,
        marginTop: 30,
        paddingTop: 5,
        paddingBottom: 5,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 1
        },
        elevation: 3,
    },
    sendTxt: {
        fontSize: 18,
        fontStyle: 'italic',
        fontWeight: 'bold',
        color: "#424b54",
    },
    icon: {
        position: 'absolute',
        right: 0,
        backgroundColor: '#5f947b',
        borderTopRightRadius: 50,
        borderBottomRightRadius: 50,
        width: 50,
        height: 35,
        paddingTop: 5,
        paddingLeft: 10,
    },
})